### PR TITLE
integrated with dashboard extension

### PR DESCRIPTION
**Pull request by Eskibear**
See https://github.com/microsoft/vscode-spring-boot-dashboard/issues/262

Requires API from:
https://github.com/microsoft/vscode-spring-boot-dashboard/pull/266

### CODE REVIEW

**Comment by Eskibear** [comment]
FYI, vscode-spring-boot-dashboard extension v0.11.0 (containing corresponding  APIs) has been released.

**Review by wangmingliang-ms — APPROVED** [review]
LGTM

**Pull request merged**
